### ISSUE TITLE
Concept design

### ISSUE THREAD

**Issue by marcinlawnik** [akai-org/trios#32]
Flow&graphics style proposal by @tomaszgil 

![small_p](https://cloud.githubusercontent.com/assets/718163/21777988/bbd75174-d6a1-11e6-8f8b-ef7e86dcaec5.png)
![img_20170108_192111204](https://cloud.githubusercontent.com/assets/718163/21777994/bf5468c8-d6a1-11e6-9de5-e5fee7af6d31.jpg)
![img_20170108_192050343](https://cloud.githubusercontent.com/assets/718163/21777996/c0cae682-d6a1-11e6-9af8-42d952ed6434.jpg)

**Comment by knopers666** [comment]
Masz to w psd?

**Comment by marcinlawnik** [comment]
Nie, zapytałem @tomaszgil gdzie to znalazł

**Comment by marcinlawnik** [comment]
Nie ma psd.

**Comment by marcinlawnik** [comment]
Flow and design implemented. Closing
