### ISSUE TITLE
Feedback po złej odpowiedzi

### ISSUE THREAD

**Issue by marcinlawnik** [akai-org/trios#39]
@hejmsdz pisze:

Po wpisaniu drugi i kolejny raz (inb4 ale ze mnie lamus) złej odpowiedzi nie ma żadnej zmiany stanu, można mieć wrażenie, że aplikacja nie przetworzyła odpowiedzi. Można by zrobić np. animację wstrząśnięcia po podaniu złego rozwiązania.

**Comment by hejmsdz** [comment]
Done.
