### ISSUE TITLE
System zapisu zmian

### ISSUE THREAD

**Issue by marcinlawnik** [akai-org/trios#9]
Gdy dodamy już możliwość edycji trios, fajnie byłoby wiedzieć kto co zmienił, taki log tylko w bazie danych żeby nic nie zginęło.

**Comment by MichalDolata** [comment]
Taki system nam wystarczy, czy potrzebujemy czegoś bardziej zaawansowanego?

**Comment by marcinlawnik** [comment]
Jak na razie myślę, że tak.
